feat:トップページのRead機能をDDD構造化
yuta10200831/7-15.docker-templete pull request #38
Opened 2024-02-19 13:58 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/9-55-47bd0d05b1c54269bb1afb0760542b60

## 作業詳細
topページのRead機能をDDD構造化しました。
ご確認宜しくお願いします！

2024-02-20 06:25 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-02-20 06:25 UTC, KatsuyaTanaka95 commented on src/public/index.php
> +    $indexDao = new IndexDao();
daoは、テーブル１つに対して１つ作成するようにしましょう！！
https://www.notion.so/2-1758b8c7441944bc8206cebc259a7459?pvs=4#e63dc2814ff547e59480ae2617775972
（教材に書いてあるものが抜けてしまっているので、再度全体的に読みましょう！）
<img width="1440" alt="スクリーンショット 2024-02-20 15 20 13" src="https://github.com/yuta10200831/7-15.docker-templete/assets/63081802/4e53208d-753d-4b63-8700-692f2d31e500">

なので、、今回は、「QueryServise」内で、「支出を取得するDao」と「収入を取得するDao」を使用するようにしましょう！！

2024-02-20 14:58 UTC, yuta10200831 commented on src/public/index.php
> +    $indexDao = new IndexDao();
レビューありがとうございます。
incomesDao,spendingsDaoを使う所まではわかっていたのですが、最終的にindexDaoを作成する事でまとめてしまいました。
改めて田中さんにレビュー頂いた箇所のカリキュラムを読み返し、コードの修正を行いました。
ご確認宜しくお願い致します！

2024-02-21 03:54 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

index.phpのPHPコードの部分がコード量が少し多めなので、手が空いてしまった際には、UseCaseをに作ってもいいかもしれません！

2024-02-21 14:10 UTC, merged