feat:収入一覧のDDD構造化
yuta10200831/7-15.docker-templete pull request #39
Opened 2024-02-20 05:30 UTC by yuta10200831

2024-02-21 03:59 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-02-21 03:59 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInput/IncomesReadInput.php
> +    public function __construct($incomeSourceId, $startDate, $endDate)
引数に型をしていしましょう！！
型を指定しないとこのクラスを作る意味がなくなってしまうので、、、

2024-02-21 03:59 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInput/IncomesReadInput.php
> +    }
メソッドの返り値に型をしていしましょう！！
型を指定しないとこのクラスを作る意味がなくなってしまうので、、、

2024-02-21 14:26 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInput/IncomesReadInput.php
> +    public function __construct($incomeSourceId, $startDate, $endDate)
承知致しました！
修正致しましたのでご確認宜しくお願いします！

2024-02-21 14:26 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInput/IncomesReadInput.php
> +    }
承知致しました！
ご確認宜しくお願いします！ｚ

2024-02-26 03:36 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-02-26 11:14 UTC, merged