feat:カテゴリ一覧画面のDDD構造化
yuta10200831/7-15.docker-templete pull request #42
Opened 2024-02-22 08:59 UTC by yuta10200831

作業対象
[作業をした教材のURL]
https://www.notion.so/9-55-47bd0d05b1c54269bb1afb0760542b60

作業詳細
カテゴリ一覧画面のRead機能をDDD構造化しました。
ご確認宜しくお願いします！

2024-02-26 03:45 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-02-26 03:45 UTC, KatsuyaTanaka95 commented on src/public/spendings/category/index.php
> +    $categoryInput = new CategoryReadInput('');
外から（フォーム等から）受け取るデータがない場合は、UseCaseInputはなくてOKです！！
UseCaseInputは削除しましょう！！

2024-02-27 01:43 UTC, yuta10200831 commented on src/public/spendings/category/index.php
> +    $categoryInput = new CategoryReadInput('');
承知致しました！
修正しましたのでご確認宜しくお願いします！

2024-02-27 22:14 UTC, KatsuyaTanaka95 approved these changes
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-02-28 04:40 UTC, merged