feat:支出一覧編集機能のDDD構造化
yuta10200831/7-15.docker-templete pull request #45
Opened 2024-03-01 01:29 UTC by yuta10200831

## 作業対象
[作業をした教材のURL]
https://www.notion.so/7-50-e43702123b2541678d2f727e16905d72

## 作業詳細
支出一覧之編集機能をDDD構造化しました。
ご確認よろしくお願いします。

2024-03-05 23:46 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いいたします！🙆🙋😊🌟💫

2024-03-05 23:46 UTC, KatsuyaTanaka95 commented on src/public/spendings/edit.php
> +$categories = $spendingsQueryService->getCategories();
カテゴリデータの取得は、CategoryQueryService.phpでおこないましょう！！

2024-03-05 23:46 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseInput/SpendingsEditInput.php
> +}
それぞれの値を返すメソッドを作成しましょう！！！

2024-03-05 23:46 UTC, KatsuyaTanaka95 commented on src/app/UseCase/UseCaseOutput/SpendingsEditOutput.php
> +}
それぞれの値を返すメソッドを作成しましょう！！！

2024-03-06 02:07 UTC, yuta10200831 commented on src/app/UseCase/UseCaseInput/SpendingsEditInput.php
> +}
承知致しました！
修正したので改めてご確認よろしくお願いします。

2024-03-06 02:07 UTC, yuta10200831 commented on src/app/UseCase/UseCaseOutput/SpendingsEditOutput.php
> +}
承知致しました！
修正したのでご確認宜しくお願いします！

2024-03-06 03:16 UTC, yuta10200831 commented on src/public/spendings/edit.php
> +$categories = $spendingsQueryService->getCategories();
修正致しました！
ご確認よろしくお願い致します。

2024-03-06 21:48 UTC, KatsuyaTanaka95 approved these changes
ご修正ありがとうございます！
LGTMです！！！
mergeしちゃいましょ〜🙆🙋😊🌟💫

2024-03-07 02:58 UTC, merged